tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/cask-fonts"
tap "koekeishiya/formulae"
tap "cjbassi/ytop"

brew "asdf"
brew "awscli"
brew "bat"
brew "curl"
brew "direnv"
brew "exa"
brew "gh"
brew "ghq"
brew "git"
brew "jq"
brew "mas"
brew "peco"
brew "rcm"
brew "starship"
brew "stow"
brew "starship"
brew "ytop"
brew "yarn"
brew "zinit"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"

cask "alacritty"
cask "alfred"
cask "appcleaner"
cask "authy"
cask "deepl"
cask "discord"
cask "docker"
cask "font-hack-nerd-font"
cask "google-chrome"
cask "google-japanese-ime"
cask "iterm2"
cask "jetbrains-toolbox"
cask "karabiner-elements"
cask "notion"
cask "postman"
cask "slack"
cask "stoplight-studio"
cask "visual-studio-code"

mas "Just Focus", id: 1142151959
mas "Magnet", id: 441258766
mas "Spark", id: 1176895641
mas "PopClip", id: 445189367
