tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/cask-fonts"
tap "koekeishiya/formulae"
tap "cjbassi/ytop"

brew "asdf"
brew "awscli"
brew "bat"
brew "curl"
brew "exa"
brew "ghq"
brew "git"
brew "jq"
brew "mas"
brew "peco"
brew "rcm"
brew "skhd"
brew "starship"
brew "stow"
brew "starship"
brew "yabai"
brew "ytop"
brew "yarn"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"

cask "alacritty"
cask "alfred"
cask "appcleaner"
cask "discord"
cask "docker"
cask "font-hack-nerd-font"
cask "google-chrome"
cask "google-japanese-ime"
cask "jetbrains-toolbox"
cask "karabiner-elements"
cask "notion"
cask "postman"
cask "slack"
cask "visual-studio-code"
cask "zoom"

mas "Just Focus", id: 1142151959
mas "LINE", id: 539883307
mas "Spark", id: 1176895641
mas "PopClip", id: 445189367
