#!/usr/bin/env sh

## ----------------------------------------
## Base Settings
## ----------------------------------------
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autoraise
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_shadow                off
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                off
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xff7465FF
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xaad75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

## ----------------------------------------
## Space Settings
## ----------------------------------------
yabai -m config layout                       bsp
yabai -m config top_padding                  6
yabai -m config bottom_padding               6
yabai -m config left_padding                 6
yabai -m config right_padding                6
yabai -m config window_gap                   6
yabai -m config --space 2 layout             stack
yabai -m config --space 7 layout             float

## ----------------------------------------
## Ignore Settings
## ----------------------------------------
yabai -m rule --add app="^Finder" manage=off
yabai -m rule --add app="^Preview" manage=off
yabai -m rule --add app="^FaceTime" manage=off
yabai -m rule --add app="^QuickTime Player" manage=off
yabai -m rule --add app="^System Preferences" manage=off
yabai -m rule --add app="^Slack" manage=off
yabai -m rule --add app="^Discord" manage=off
yabai -m rule --add app="^Spark" manage=off
yabai -m rule --add app="^JetBrains Toolbox" manage=off
yabai -m rule --add app="^Authy Desktop" manage=off
yabai -m rule --add app="^Notion" manage=off
yabai -m rule --add app="^zoom" manage=off
yabai -m rule --add app="^ミュージック" manage=off
yabai -m rule --add app="^カレンダー" manage=off
yabai -m rule --add app="^システム環境設定" manage=off
yabai -m rule --add app="^Todoist" manage=off
yabai -m rule --add app="^LINE" manage=off
yabai -m rule --add app="^App Store" manage=off
yabai -m rule --add app="^DataGrip" manage=off
yabai -m rule --add app="^Messenger" manage=off
yabai -m rule --add app="^DeepL" manage=off

echo "yabai configuration loaded.."

